FROM python:3-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
                      ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt

CMD ["/bin/bash"]